"""pyforge CLI — auto test generator for Python files."""

import argparse
import os
import sys
from pathlib import Path

from pyforge.analysis.python_ast import (
    analyze_python,
    detect_framework,
    detect_lang,
    project_root,
)
from pyforge.coverage import (
    find_uncovered_methods,
    parse_missing_coverage,
    resolve_api_test_path,
    resolve_test_path,
    run_coverage,
)
from pyforge.renderers.api_renderer import detect_api_framework, generate_api_tests
from pyforge.renderers.pytest_renderer import generate_python_test_file
from pyforge.renderers.db_integration_renderer import generate_db_integration_block


def die(msg: str) -> None:
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def info(msg: str) -> None:
    print(f"[pyforge] {msg}")


def _confirm_execute_capture(args) -> bool:
    """Ask user for confirmation if --execute-capture is set but --yes is not."""
    if not args.execute_capture:
        return False
    if args.yes:
        return True
    # Prompt user
    print("[pyforge] --execute-capture imports and runs your module. Side effects may occur.")
    response = input("Proceed? [y/N]: ").strip().lower()
    return response == "y"


def _build_arg_parser():
    p = argparse.ArgumentParser(
        description="Auto test generator for Python files (pytest)."
    )
    p.add_argument("target", help="Path to the Python source file")
    p.add_argument("--integration", action="store_true",
                   help="Generate integration tests (tests/integration/)")
    p.add_argument("--api", action="store_true",
                   help="Generate API/HTTP endpoint tests")
    p.add_argument(
        "--coverage", type=int,
        default=int(os.getenv("COVERAGE_THRESHOLD", "90")),
        help="Coverage threshold percent (default: 90)",
    )
    p.add_argument(
        "--mode",
        choices=["minimal", "standard", "exhaustive"],
        default="standard",
        help=(
            "minimal=branches+happy-path only; "
            "standard=+boundary+null+defaults+enum; "
            "exhaustive=all strategies"
        ),
    )
    p.add_argument(
        "--execute-capture",
        action="store_true",
        help=(
            "[opt-in] Import and execute the module to capture return values. "
            "WARNING: runs module-level code (may have side effects)."
        ),
    )
    p.add_argument(
        "-y", "--yes",
        action="store_true",
        help="Skip all confirmations (useful for CI). Required to use --execute-capture without prompting.",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated tests to stdout without writing files. No coverage check is run.",
    )
    p.add_argument(
        "--db-integration",
        action="store_true",
        help=(
            "Append a real DB integration test class and generate conftest.py. "
            "Activates only when DB dependencies (sqlalchemy, django.db, psycopg2, etc.) "
            "are detected in the source file."
        ),
    )
    return p


def main():
    args = _build_arg_parser().parse_args()

    target = Path(args.target).resolve()
    if not target.exists():
        die(f"File not found: {target}")

    # If target is a directory, process all Python files recursively
    if target.is_dir():
        python_files = sorted(target.glob("**/*.py"))
        if not python_files:
            die(f"No Python files found in {target}")
        info(f"Found {len(python_files)} Python file(s)")
        for py_file in python_files:
            info(f"Processing: {py_file}")
            _process_file(py_file, args)
        return

    # Single file mode
    _process_file(target, args)


def _handle_api_mode(args, target: Path, root: Path, source_text: str, module_path: str) -> bool:
    """Handle API mode. Returns True if API mode was executed, False otherwise."""
    api_framework = detect_api_framework(source_text)
    if not (args.api or api_framework):
        return False

    if not api_framework:
        die("No API routes detected in this file.")

    # Log if API was auto-detected (not explicitly requested)
    if api_framework and not args.api:
        info(f"API framework detected automatically ({api_framework}). Pass --api to suppress this message.")
    else:
        info(f"API framework: {api_framework}")
    content = generate_api_tests(source_text, api_framework, module_path, source_path=target)
    if not content:
        info("WARNING: No endpoints detected. Writing failing stub test.")
        content = (
            '"""Generated by pyforge — no API endpoints could be detected."""\n\n'
            f'def test_no_api_endpoints_detected():\n'
            f'    assert False, (\n'
            f'        "pyforge could not detect any API endpoints in {target.name!r}. "\n'
            f'        "Review the source and re-run, or write API tests manually."\n'
            f'    )\n'
        )

    if getattr(args, 'dry_run', False) is True:
        print("\n=== DRY RUN: API Tests ===")
        print(content)
        print("=== END DRY RUN ===\n")
    else:
        try:
            test_path = resolve_api_test_path(target, root)
            test_path.parent.mkdir(parents=True, exist_ok=True)
            test_path.write_text(content)
            info(f"API test written: {test_path}")
        except Exception as e:
            die(f"Failed to write API test file: {e}")

    return True


def _handle_unit_mode(args, target: Path, root: Path, src_info, test_path: Path) -> tuple[str, bool]:
    """Generate unit/integration tests. Returns (content, should_continue)."""
    info(f"Methods found: {[m.name for m in src_info.methods]}")
    info(f"External deps: {[d.name for d in src_info.external_deps]}")
    if not args.dry_run:
        info(f"Test output: {test_path}")

    # incremental mode: check what's already covered
    if test_path.exists() and not args.dry_run:
        info("Existing test file found — checking for uncovered methods...")
        uncovered = find_uncovered_methods(src_info, test_path)
        if not uncovered:
            info("All methods covered. Nothing to add.")
            return "", False
        info(f"Uncovered: {[m.name for m in uncovered]}")
        src_info.methods = uncovered

    # Confirm execute-capture if needed
    execute_capture = _confirm_execute_capture(args)

    # generate skeleton via static analysis
    content = generate_python_test_file(
        target, root, src_info, args.coverage,
        mode=args.mode,
        execute_capture=execute_capture,
    )
    info("Skeleton generated statically (no Claude call).")

    # write or print test file
    if getattr(args, 'dry_run', False) is True:
        print("\n=== DRY RUN: Unit Tests ===")
        print(content)
        print("=== END DRY RUN ===\n")
    else:
        try:
            test_path.parent.mkdir(parents=True, exist_ok=True)
            if test_path.exists():
                existing = test_path.read_text()
                test_path.write_text(existing.rstrip() + "\n\n" + content)
            else:
                test_path.write_text(content)
            info(f"Written: {test_path}")
        except Exception as e:
            die(f"Failed to write test file {test_path}: {e}")

    # Skip further processing if no tests were generated
    if not content.strip():
        info("No tests generated. Skipping coverage check.")
        return content, False

    return content, True


def _append_db_integration(args, target: Path, root: Path, src_info, test_path: Path) -> None:
    """Append DB integration tests if --db-integration is passed."""
    if not args.db_integration or args.dry_run:
        return

    integration_block, conftest_content = generate_db_integration_block(target, root, src_info)
    if integration_block:
        try:
            test_path.write_text(test_path.read_text().rstrip() + "\n\n" + integration_block)
            info("DB integration test class appended.")
            conftest_path = test_path.parent / "conftest.py"
            if conftest_path.exists():
                info(f"conftest.py already exists at {conftest_path} — skipping (merge manually).")
            else:
                conftest_path.write_text(conftest_content)
                info(f"conftest.py written: {conftest_path}")
        except Exception as e:
            die(f"Failed to write DB integration files: {e}")
    else:
        info("--db-integration passed but no DB dependencies detected — skipping.")


def _run_coverage_check(args, test_path: Path, root: Path, target: Path) -> None:
    """Run coverage check if not in integration or dry-run mode."""
    if args.integration or args.dry_run:
        return

    success, stdout = run_coverage(test_path, root, args.coverage, target=target)
    if success:
        info(f"Coverage ≥ {args.coverage}% achieved.")
    else:
        info(f"WARNING: Coverage below {args.coverage}%. Review and add tests manually.")
        missing = parse_missing_coverage(stdout)
        if missing:
            info("Files with low coverage:")
            for item in missing:
                info(f"  - {item}")
            info("Re-run with --mode exhaustive to generate more test cases.")
        sys.exit(1)


def _process_file(target: Path, args):
    """Process a single Python file."""
    lang = detect_lang(target)
    root = project_root(target)
    framework = detect_framework(lang, root)
    info(f"Language: {lang} / {framework}")

    source_text = target.read_text()
    try:
        rel = target.relative_to(root).with_suffix("")
        module_path = ".".join(rel.parts)
    except ValueError:
        module_path = target.stem

    # API mode (early exit if matched)
    if _handle_api_mode(args, target, root, source_text, module_path):
        return

    # Unit / integration mode
    src_info = analyze_python(target, root)
    test_path = resolve_test_path(target, root, args.integration)
    content, should_continue = _handle_unit_mode(args, target, root, src_info, test_path)

    if not should_continue:
        return

    # DB integration and coverage checks
    _append_db_integration(args, target, root, src_info, test_path)
    _run_coverage_check(args, test_path, root, target)

    info(f"Done: {test_path}")


if __name__ == "__main__":
    main()
